#!/bin/sh

set -e

# Simply multiplexes arguments over both simulator and device cabals

#i386-apple-darwin11-cabal $@
#arm-apple-darwin10-cabal $@
aarch64-apple-darwin16-cabal $@
x86_64-apple-darwin16-cabal $@
