#!/bin/sh
export COMMON=--builddir=dist/x86_64
export COMPILE="--with-ghc=x86_64-apple-darwin16-ghc
                --with-ghc-pkg=x86_64-apple-darwin16-ghc-pkg
                --with-gcc=x86_64-apple-darwin16-clang
                --with-ld=x86_64-apple-darwin16-ld
                --hsc2hs-options=--cross-compile"
export CONFIG="--configure-option=--host=x86_64-apple-darwin16 --disable-shared"
exec "`dirname $0`/common-cross-cabal" "$@"
